Document: freeswitch
Title: Debian freeswitch Manual
Author: <insert document author here>
Abstract: This manual describes what freeswitch is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/freeswitch/freeswitch.sgml.gz

Format: postscript
Files: /usr/share/doc/freeswitch/freeswitch.ps.gz

Format: text
Files: /usr/share/doc/freeswitch/freeswitch.text.gz

Format: HTML
Index: /usr/share/doc/freeswitch/html/index.html
Files: /usr/share/doc/freeswitch/html/*.html
